pipeline {
    agent any

    environment {
        APP_NAME = "${{values.app_name}}".toLowerCase()
        DOCKER_IMAGE = "jaykumark7/${APP_NAME}"
        DOCKER_TAG = "1.0.${BUILD_NUMBER}"
        IMAGE_TAG = "${DOCKER_IMAGE}:${DOCKER_TAG}"
        GITOPS_REPO = "https://github.com/jkgoldenimageorg/k8s-manifest.git"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${IMAGE_TAG} .
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'jk7-dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                    docker push ${IMAGE_TAG}
                '''
            }
        }

        stage('Update GitOps Repo') {
            steps {
                withCredentials([string(credentialsId: 'jk7-github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git clone https://${GITHUB_TOKEN}@github.com/jkgoldenimageorg/k8s-manifest.git
                        cd k8s-manifest
        
                        mkdir -p apps/${APP_NAME}
        
                        cp -r ../manifest-templates/* apps/${APP_NAME}/
        
                        sed -i "s|\\${APP_NAME}|${APP_NAME}|g" apps/${APP_NAME}/*.yaml
                        sed -i "s|\\${DOCKER_IMAGE}|${IMAGE_TAG}|g" apps/${APP_NAME}/deployment.yaml
        
                        git config --global --add safe.directory '*'
                        git config user.email "jenkins@local"
                        git config user.name "jenkins"
        
                        git add .
                        git commit -m "Deploy ${APP_NAME} build ${BUILD_NUMBER}" || true
                        git push
                    '''
                }
            }
        }

    }

    post {
        always {
            sh "docker logout || true"
            sh "docker image prune -f || true"
        }
        success {
            echo "CI + CD pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}









